-- AUTO-GENERATED by Theoremforces. Do not edit by hand.
-- Challenge: calc-shifted-square-nonneg
-- Submission: cmpjn0dff0001521u8xlsqgnj

import Mathlib

namespace Theoremforces.Challenges.User.U_calc_shifted_square_nonneg.Submissions.Submission_cmpjn0dff0001521u8xlsqgnj

-- ┌── USER SUBMISSION BODY (verbatim) ─────────────────────
-- The app appends:
--   def solution_target : ∀ (a x : ℝ), 0 ≤ (x - a) ^ 2 := answer
-- so define `answer` with that type.

theorem answer (a x : ℝ) : 0 ≤ (x - a) ^ 2 := by
  exact sq_nonneg (x - a)
-- └── USER SUBMISSION BODY END ────────────────────────────

/-- App-appended type check. Refuses to compile unless
    `answer` has type `∀ (a x : ℝ), 0 ≤ (x - a) ^ 2`. -/
def solution_target : ∀ (a x : ℝ), 0 ≤ (x - a) ^ 2 := answer

#print axioms solution_target

end Theoremforces.Challenges.User.U_calc_shifted_square_nonneg.Submissions.Submission_cmpjn0dff0001521u8xlsqgnj
