-- AUTO-GENERATED by Theoremforces. Do not edit by hand.
-- Challenge: calc-quadratic-vertex-minimizes
-- Submission: cmpk3wz8600014h1uiqqba2oq

import Mathlib

namespace Theoremforces.Challenges.User.U_calc_quadratic_vertex_minimizes.Submissions.Submission_cmpk3wz8600014h1uiqqba2oq

-- ┌── USER SUBMISSION BODY (verbatim) ─────────────────────
-- The app appends:
--   def solution_target : ∀ (b c x : ℝ), (-b / 2) ^ 2 + b * (-b / 2) + c ≤ x ^ 2 + b * x + c := answer
-- so define `answer` with that type.

theorem answer (b c x : ℝ) : (-b / 2) ^ 2 + b * (-b / 2) + c ≤ x ^ 2 + b * x + c := by
  si


-- └── USER SUBMISSION BODY END ────────────────────────────

/-- App-appended type check. Refuses to compile unless
    `answer` has type `∀ (b c x : ℝ), (-b / 2) ^ 2 + b * (-b / 2) + c ≤ x ^ 2 + b * x + c`. -/
def solution_target : ∀ (b c x : ℝ), (-b / 2) ^ 2 + b * (-b / 2) + c ≤ x ^ 2 + b * x + c := answer

#print axioms solution_target

end Theoremforces.Challenges.User.U_calc_quadratic_vertex_minimizes.Submissions.Submission_cmpk3wz8600014h1uiqqba2oq
