-- AUTO-GENERATED by Theoremforces. Do not edit by hand.
-- Challenge: nat-mul-zero
-- Submission: cmpjdumgq0003tg1uwrec5jwr

import Mathlib

namespace Theoremforces.Challenges.User.U_nat_mul_zero.Submissions.Submission_cmpjdumgq0003tg1uwrec5jwr

-- ┌── USER SUBMISSION BODY (verbatim) ─────────────────────
-- The app appends:
--   def solution_target : ∀ (n : Nat), n * 0 = 0 := answer
-- so define `answer` with that type.

theorem answer (n : Nat) : n * 0 = 0 := by
  ring

-- └── USER SUBMISSION BODY END ────────────────────────────

/-- App-appended type check. Refuses to compile unless
    `answer` has type `∀ (n : Nat), n * 0 = 0`. -/
def solution_target : ∀ (n : Nat), n * 0 = 0 := answer

#print axioms solution_target

end Theoremforces.Challenges.User.U_nat_mul_zero.Submissions.Submission_cmpjdumgq0003tg1uwrec5jwr

-- backfill rerun 20260524T215553
