-- AUTO-GENERATED by Leanforces. Do not edit by hand.
-- Challenge: nat-mul-zero
-- Submission: cmpid3ljg0001x21rv6rplu3s

import Mathlib

namespace Theoremforces.Challenges.User.U_nat_mul_zero.Submissions.Submission_cmpid3ljg0001x21rv6rplu3s

-- ┌── USER SUBMISSION BODY (verbatim) ─────────────────────
-- The app appends:
--   def solution_target : ∀ (n : Nat), n * 0 = 0 := answer
-- so define `answer` with that type.

theorem answer (n : Nat) : n * 0 = 0 := by
  simp
-- └── USER SUBMISSION BODY END ────────────────────────────

/-- App-appended type check. Refuses to compile unless
    `answer` has type `∀ (n : Nat), n * 0 = 0`. -/
def solution_target : ∀ (n : Nat), n * 0 = 0 := answer

#print axioms solution_target

end Theoremforces.Challenges.User.U_nat_mul_zero.Submissions.Submission_cmpid3ljg0001x21rv6rplu3s
