-- AUTO-GENERATED by Theoremforces. Do not edit by hand.
-- Challenge: group-solve-right-mul-equation
-- Submission: cmpk9ilpz0001zi1uyw40hd07

import Mathlib

namespace Theoremforces.Challenges.User.U_group_solve_right_mul_equation.Submissions.Submission_cmpk9ilpz0001zi1uyw40hd07

-- ┌── USER SUBMISSION BODY (verbatim) ─────────────────────
-- The app appends:
--   def solution_target : ∀ {G : Type*} [Group G] (a b x : G), x * a = b ↔ x = b * a⁻¹ := answer
-- so define `answer` with that type.

theorem answer {G : Type*} [Group G] (a b x : G) : x * a = b ↔ x = b * a⁻¹ := by
  constructor
  · intro h
    rw [← h]
    simp
  · intro h
    rw [h]
    simp


-- └── USER SUBMISSION BODY END ────────────────────────────

/-- App-appended type check. Refuses to compile unless
    `answer` has type `∀ {G : Type*} [Group G] (a b x : G), x * a = b ↔ x = b * a⁻¹`. -/
def solution_target : ∀ {G : Type*} [Group G] (a b x : G), x * a = b ↔ x = b * a⁻¹ := answer

#print axioms solution_target

end Theoremforces.Challenges.User.U_group_solve_right_mul_equation.Submissions.Submission_cmpk9ilpz0001zi1uyw40hd07
