-- AUTO-GENERATED by Theoremforces. Do not edit by hand.
-- Challenge: calc-deriv-affine
-- Submission: cmpkb572b0001xg1ugqeot684

import Mathlib

namespace Theoremforces.Challenges.User.U_calc_deriv_affine.Submissions.Submission_cmpkb572b0001xg1ugqeot684

-- ┌── USER SUBMISSION BODY (verbatim) ─────────────────────
-- The app appends:
--   def solution_target : ∀ (a b x : ℝ), HasDerivAt (fun y : ℝ => a * y + b) a x := answer
-- so define `answer` with that type.

theorem answer (a b x : ℝ) : HasDerivAt (fun y : ℝ => a * y + b) a x := by
  simpa using ((hasDerivAt_id x).const_mul a).add_const b
-- └── USER SUBMISSION BODY END ────────────────────────────

/-- App-appended type check. Refuses to compile unless
    `answer` has type `∀ (a b x : ℝ), HasDerivAt (fun y : ℝ => a * y + b) a x`. -/
def solution_target : ∀ (a b x : ℝ), HasDerivAt (fun y : ℝ => a * y + b) a x := answer

#print axioms solution_target

end Theoremforces.Challenges.User.U_calc_deriv_affine.Submissions.Submission_cmpkb572b0001xg1ugqeot684
