-- AUTO-GENERATED by Theoremforces. Do not edit by hand.
-- Challenge: rank-nullity-linear-map-finrank
-- Submission: cmpkdn7nv0001wq1uu5fglb8u

import Mathlib

namespace Theoremforces.Challenges.User.U_rank_nullity_linear_map_finrank.Submissions.Submission_cmpkdn7nv0001wq1uu5fglb8u

-- ┌── USER SUBMISSION BODY (verbatim) ─────────────────────
theorem answer :
    ∀ {K V W : Type*} [DivisionRing K] [AddCommGroup V] [Module K V]
      [AddCommGroup W] [Module K W] [FiniteDimensional K V] (f : V →ₗ[K] W),
      Module.finrank K (LinearMap.range f) + Module.finrank K (LinearMap.ker f) =
        Module.finrank K V := by
  intro K V W _ _ _ _ _ _ f
  exact LinearMap.finrank_range_add_finrank_ker f
-- └── USER SUBMISSION BODY END ────────────────────────────

/-- App-appended type check. Refuses to compile unless
    `answer` has type `∀ {K V W : Type*} [DivisionRing K] [AddCommGroup V] [Module K V] [AddCommGroup W] [Module K W] [FiniteDimensional K V] (f : V →ₗ[K] W), Module.finrank K (LinearMap.range f) + Module.finrank K (LinearMap.ker f) = Module.finrank K V`. -/
def solution_target : ∀ {K V W : Type*} [DivisionRing K] [AddCommGroup V] [Module K V] [AddCommGroup W] [Module K W] [FiniteDimensional K V] (f : V →ₗ[K] W), Module.finrank K (LinearMap.range f) + Module.finrank K (LinearMap.ker f) = Module.finrank K V := answer

#print axioms solution_target

end Theoremforces.Challenges.User.U_rank_nullity_linear_map_finrank.Submissions.Submission_cmpkdn7nv0001wq1uu5fglb8u
