-- AUTO-GENERATED by Theoremforces. Do not edit by hand.
-- Challenge: user-theorem-42e16ba5
-- Submission: cmpkcwohg0003uq1uydxyfv9e

import Mathlib

namespace Theoremforces.Challenges.User.SelfProven.U_user_theorem_42e16ba5.Submissions.Submission_cmpkcwohg0003uq1uydxyfv9e

-- ┌── USER SUBMISSION BODY (verbatim) ─────────────────────
theorem answer : ∀ {α : Type*} (f : α → Set α), ¬ Function.Surjective f := by
  intro α f hsurj
  let diagonal : Set α := {x | x ∉ f x}
  rcases hsurj diagonal with ⟨a, ha⟩

  have hiff : a ∈ f a ↔ a ∉ f a := by
    constructor
    · intro h
      have hd : a ∈ diagonal := by
        simpa [ha] using h
      simpa [diagonal] using hd
    · intro h
      have hd : a ∈ diagonal := by
        simpa [diagonal] using h
      simpa [ha] using hd

  have hnot : a ∉ f a := by
    intro hp
    exact (hiff.mp hp) hp

  exact hnot (hiff.mpr hnot)
-- └── USER SUBMISSION BODY END ────────────────────────────

/-- App-appended type check. Refuses to compile unless
    `answer` has type `∀ {α : Type*} (f : α → Set α), ¬ Function.Surjective f`. -/
def solution_target : ∀ {α : Type*} (f : α → Set α), ¬ Function.Surjective f := answer

#print axioms solution_target

end Theoremforces.Challenges.User.SelfProven.U_user_theorem_42e16ba5.Submissions.Submission_cmpkcwohg0003uq1uydxyfv9e
