-- AUTO-GENERATED by ProofGarden Lean Judge. Do not edit by hand.
-- Challenge: C0002
-- Submission: cmpgy3b8x000111l6zxdyfoh2

import Mathlib

namespace ProofGarden.Challenges.C0002.Submissions.S_cmpgy3b8x000111l6zxdyfoh2

-- ┌── USER SUBMISSION BODY (verbatim) ─────────────────────
theorem answer {R : Type _} [CommRing R] (a b : R) : (a + b)^2 = a^2 + 2*a*b + b^2 := by ring
-- └── USER SUBMISSION BODY END ────────────────────────────

/-- App-appended type check. Refuses to compile unless
    `answer` has type `∀ {R : Type _} [CommRing R] (a b : R), (a + b)^2 = a^2 + 2*a*b + b^2`. -/
def solution_target : ∀ {R : Type _} [CommRing R] (a b : R), (a + b)^2 = a^2 + 2*a*b + b^2 := answer

#print axioms solution_target

end ProofGarden.Challenges.C0002.Submissions.S_cmpgy3b8x000111l6zxdyfoh2
