-- AUTO-GENERATED by Theoremforces. Do not edit by hand.
-- Challenge: calc-complete-square
-- Submission: cmpk3qxyy0001031unrfduv5y

import Mathlib

namespace Theoremforces.Challenges.User.U_calc_complete_square.Submissions.Submission_cmpk3qxyy0001031unrfduv5y

-- ┌── USER SUBMISSION BODY (verbatim) ─────────────────────
-- The app appends:
--   def solution_target : ∀ (b c x : ℝ), x ^ 2 + b * x + c = (x + b / 2) ^ 2 + c - b ^ 2 / 4 := answer
-- so define `answer` with that type.

theorem answer (b c x : ℝ) : x ^ 2 + b * x + c = (x + b / 2) ^ 2 + c - b ^ 2 / 4 := by
  simp


-- └── USER SUBMISSION BODY END ────────────────────────────

/-- App-appended type check. Refuses to compile unless
    `answer` has type `∀ (b c x : ℝ), x ^ 2 + b * x + c = (x + b / 2) ^ 2 + c - b ^ 2 / 4`. -/
def solution_target : ∀ (b c x : ℝ), x ^ 2 + b * x + c = (x + b / 2) ^ 2 + c - b ^ 2 / 4 := answer

#print axioms solution_target

end Theoremforces.Challenges.User.U_calc_complete_square.Submissions.Submission_cmpk3qxyy0001031unrfduv5y

-- backfill rerun 20260524T215557
