-- AUTO-GENERATED by Theoremforces. Do not edit by hand.
-- Challenge: thales-coordinate-semicircle
-- Submission: cmpkbmwhx0001201unxs2poqx

import Mathlib

namespace Theoremforces.Challenges.User.U_thales_coordinate_semicircle.Submissions.Submission_cmpkbmwhx0001201unxs2poqx

-- ┌── USER SUBMISSION BODY (verbatim) ─────────────────────
theorem answer (r x y : ℝ) :
    x ^ 2 + y ^ 2 = r ^ 2 → (x + r) * (x - r) + y ^ 2 = 0 := by
  intro h
  nlinarith
-- └── USER SUBMISSION BODY END ────────────────────────────

/-- App-appended type check. Refuses to compile unless
    `answer` has type `∀ (r x y : ℝ), x ^ 2 + y ^ 2 = r ^ 2 → (x + r) * (x - r) + y ^ 2 = 0`. -/
def solution_target : ∀ (r x y : ℝ), x ^ 2 + y ^ 2 = r ^ 2 → (x + r) * (x - r) + y ^ 2 = 0 := answer

#print axioms solution_target

end Theoremforces.Challenges.User.U_thales_coordinate_semicircle.Submissions.Submission_cmpkbmwhx0001201unxs2poqx
