-- AUTO-GENERATED by Leanforces. Do not edit by hand.
-- Challenge: C0001
-- Submission: cmph449ms0001u9imd7fk9i8l

import Leanforces.Challenges.C0001.Statement
import Mathlib

namespace Leanforces.Challenges.C0001.Submissions.Submission_cmph449ms0001u9imd7fk9i8l

-- ┌── USER SUBMISSION BODY (verbatim) ─────────────────────
lemma h (n : Nat) : n + 0 = n := Nat.add_zero n
theorem answer (n : Nat) : n + 0 = n := h n
-- └── USER SUBMISSION BODY END ────────────────────────────

/-- App-appended type check. Refuses to compile unless
    `answer` has type `∀ (n : Nat), n + 0 = n`. -/
def solution_target : ∀ (n : Nat), n + 0 = n := answer

#print axioms solution_target

end Leanforces.Challenges.C0001.Submissions.Submission_cmph449ms0001u9imd7fk9i8l
