-- AUTO-GENERATED by ProofGarden Lean Judge. Do not edit by hand.
-- Challenge: C0001

import ProofGarden.Challenges.C0001.Statement

namespace ProofGarden.Challenges.C0001

theorem solution (n : Nat) : n + 0 = n := by
  exact Nat.add_zero n

#print axioms solution

end ProofGarden.Challenges.C0001
